actions:
  pre:
    set_permissions: "bash -c 'chmod +x ~/dotfiles/dotfiles/config/flatpak_installer_apps.sh'"
    flatpak_install: ~/dotfiles/dotfiles/config/flatpak_installer_apps.sh
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_config:
    src: config/ghostty/config
    dst: ~/.config/ghostty/config
  f_gnome-settings.ini:
    src: config/gnome-settings.ini
    dst: ~/.config/gnome-settings.ini
  f_flatpak_installer_apps.sh:
    src: config/flatpak_installer_apps.sh
    dst: ~/.config/flatpak_installer_apps.sh
    chmod: '755'
  f_settings.json:
    src: config/ulauncher/settings.json
    dst: ~/.config/ulauncher/settings.json
  f_catppuccin.lua:
    src: config/nvim/lua/plugins/catppuccin.lua
    dst: ~/.config/nvim/lua/plugins/catppuccin.lua
  f_dap.lua:
    src: config/nvim/lua/plugins/dap.lua
    dst: ~/.config/nvim/lua/plugins/dap.lua
  f_aliases:
    src: aliases
    dst: ~/.aliases
profiles:
  fedora:
    dotfiles:
    - f_zshrc
    - f_bashrc
    - f_config
    - f_gnome-settings.ini

    - f_flatpak_installer_apps.sh
    - f_settings.json
    - f_catppuccin.lua
    - f_dap.lua
    - f_aliases
    actions:
    - set_permissions
    - flatpak_install
