schema_version = "1.0.0"
id = "theme_drcl"
name = "drcl"
version = "1.0.2"
tagline = "A variation of Dracula dark theme"
maintainer = "Oleksii Sereda <oleksiyartist@gmail.com>"
type = "theme"
tags = ["Dark", "Colorful"]
blender_version_min = "4.3.0"
license = ["SPDX:GPL-2.0-or-later"]
